obstacle_range: 2.5
raytrace_range: 3.0
# footprint: [[x0, y0], [x1, y1], []]
robot_radius: 0.2
inflation_radius: 0.15

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_sensor_link, data_type: LaserScan, topic: /steer_bot/laser/scan, marking: true, clearing: true}
